config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'posts#index'

  resources :posts

  resources :accounts, only: [:show] do
    resource :following, only: [:show]
    resource :follower, only: [:show]
  end

  scope module: :apps do
    resource :timeline, only: [:show]
    resource :profile, only: [:show, :update]
  end

  namespace :api, defaults: { format: :json } do
    scope '/posts/:post_id' do
      resource :like, only: [:show, :create, :destroy]
      resources :comments, only: [:index, :create]
    end

    scope '/account/:account_id' do
      resource :follow, only: [:show, :create]
      resource :unfollow, only: [:create]
    end
  end
end

app/views/commons/_posts.html.haml
= render 'commons/tabs'
.post-posts
  - posts.each do |post|
    .post.post-index{data: {post_id: post.id}}
      .post-post-header
        .post-avatar
          = link_to account_path(post.user), data: { turbolinks: false } do
            = image_tag post.user.avatar_image
        .post-info
          .post-username
            %p= post.user.username
          .post-post-time
            = "#{time_ago_in_words(post.created_at)}前"

      .post-images
        - if post.images.attached?
          .main-image
            = image_tag post.images.first
          .side-images
            - post.images.drop(1).each do |image|
              = image_tag image

      .post-actions
        -if user_signed_in?
          .like-button.hidden.active-heart{ data: { method: 'delete' } }
            = image_tag 'heart-active.svg'
          .like-button.hidden.inactive-heart{ data: { method: 'post' } }
            = image_tag 'heart.svg'
          .comment-button
            =link_to post_path(post), data: { turbolinks: false } do
              = image_tag 'comment.png'
          .share-button
            = link_to "https://x.com/share?url=#{ request.url }&text=#{post.content}", target: '_blank' do
              = image_tag 'share.png'

      .post-comments
        %p.like-count= "いいね数 :  #{post.like_count}"
        %p= "#{post.user.username}  #{post.content}"

= javascript_pack_tag 'like'

app/views/commons/_profile.html.haml
.container
  .profile-header

    .profile-username
      %p= user.username

    .profile-action-button
      - if user == current_user
      - else
        .profile-follow.hidden
          %p Unfollow
        .profile-unfollow.hidden
          %p Follow

  .profile-avatar
    - if @profile.avatar.attached?
      = image_tag url_for(@profile.avatar), class: 'avatar-icon', id: 'avatar-preview'
    - else
      = image_tag 'default-avatar.png', class: 'avatar-icon', id: 'avatar-preview'

    = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
      = f.file_field :avatar, class: 'hidden', id: 'avatar-input'
      = f.submit :avatar, class: 'hidden', id: 'avatar-submit'

  .profile-info
    .my-posts
      %p.count=user.post_count
      %p.content Posts
    = link_to account_follower_path(user), data: { turbolinks: false } do
      .my-followers
        %p.count.follower-count= user.follower_count
        %p.content Followers
    = link_to account_following_path(user), data: { turbolinks: false } do
      .my-followings
        %p.count.following-count= user.following_count
        %p.content Following

  .profile-my-post-list
    - user.posts.each do |post|
      .post.post-index{data: {post_id: post.id}}
        .post-post-header
          .post-avatar
            = link_to account_path(post.user), data: { turbolinks: false } do
              = image_tag post.user.avatar_image
          .post-info
            .post-username
              %p= post.user.username
            .post-post-time
              = "#{time_ago_in_words(post.created_at)}前"

        .post-images
          - if post.images.attached?
            .main-image
              = image_tag post.images.first
            .side-images
              - post.images.drop(1).each do |image|
                = image_tag image

        .post-actions
          -if user_signed_in?
            .like-button.hidden.active-heart{ data: { method: 'delete' } }
              = image_tag 'heart-active.svg'
            .like-button.hidden.inactive-heart{ data: { method: 'post' } }
              = image_tag 'heart.svg'
            .comment-button
              =link_to post_path(post), data: { turbolinks: false } do
                = image_tag 'comment.png'
            .share-button
              = link_to "https://x.com/share?url=#{ request.url }&text=#{post.content}", target: '_blank' do
                = image_tag 'share.png'

        .post-comments
          %p.like-count= "いいね数 :  #{post.like_count}"
          %p= "#{post.user.username}  #{post.content}"

= javascript_pack_tag 'like'

app/views/commons/_tabs.html.haml
.tabs
  .tabs-item{class: "#{add_active_class(posts_path)}"}
    = link_to 'All Post', posts_path, data: { turbolinks: false }
  .tabs-item{class: "#{add_active_class(timeline_path)}"}
    = link_to 'Timeline', timeline_path, data: { turbolinks: false }