config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'posts#index'

  resources :posts

  resources :accounts, only: [:show] do
    resource :following, only: [:show]
    resource :follower, only: [:show]
  end

  scope module: :apps do
    resource :timeline, only: [:show]
    resource :profile, only: [:show, :update]
  end

  namespace :api, defaults: { format: :json } do
    scope '/posts/:post_id' do
      resource :like, only: [:show, :create, :destroy]
      resources :comments, only: [:index, :create]
    end

    scope '/account/:account_id' do
      resource :follow, only: [:show, :create]
      resource :unfollow, only: [:create]
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %title HajimaruInstagram
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "https://fonts.googleapis.com", rel: "preconnect"}/
    %link{crossorigin: "", href: "https://fonts.gstatic.com", rel: "preconnect"}/
    %link{href: "https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap", rel: "stylesheet"}/
  %body
    %header.header
      .header-logos
        - if current_page?(new_post_path)
        - elsif current_page?(root_path) || current_page?(posts_path)
          = link_to new_post_path, data: { turbolinks: false } do
            .post-create-icon
              = image_tag 'photo-camera.png'
        - else
          = link_to :back, data: { turbolinks: false } do
            = image_tag 'back-icon.png', class: 'header-back'
      = link_to 'HajimaruGram', posts_path, data: { turbolinks: false }, class: 'header-title'
      - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: 'header-avatar dropbtn --icon'
          .dropdown-content
            = link_to 'プロフィール', profile_path, data: { turbolinks: false }
            = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }

    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{class: 'key'}= value
    = yield